#!/bin/sh

capacity=$(cat /sys/class/power_supply/BAT0/capacity)
status=$(sed "s/[Dd]ischarging/🔋/;s/[Nn]ot charging/🛑/;s/[Cc]harging/🔌/;s/[Uu]nknown/♻️/;s/[Ff]ull/⚡/" /sys/class/power_supply/BAT0/status)

[ "$capacity" -le 20 ] && [ "$status" = "🔋" ] && warn="❗"

printf "%s%s%s%%" "$status" "$warn" "$capacity"
