#!/bin/bash

pgrep -x dmenu && exit
source "${HOME}/.config/dmenu.conf"

mountableAndroid=$(simple-mtpfs -l)
chosen=$(echo "$mountableAndroid" | ${dmenucmd} -p "Which android")
name=$(echo $chosen | awk '{print $2}')
[[ "$name" == "" ]] && name=$(xxd -l 16 -c 16 -p < /dev/random)
id=$(echo $chosen | cut -d : -f 1)

doas mkdir /mnt/"$name"
doas simple-mtpfs --device "$id" /mnt/"$name"
