#!/bin/bash

pgrep -x dmenu && exit
source "${HOME}/.config/dmenu.conf"

vtuber=$(echo -e "Airani\nAkirose\nAmelia\nAnya\nAqua\nAruran\nAstel\nAyame\nAzki\nBaelz\nBotan\nCalliope\nChoco\nFauna\nFlare\nFubuki\nGura\nHaachama\nHolostars\nIna\nHV Indonesia\nIrys\nIzuru\nKanata\nKiara\nKorone\nKronii\nLamy\nLuna\nMarine\nMatsuri\nMel\nMiko\nMio\nMiyabi\nMoona\nNanashi\nNene\nNoel\nOga\nOkayu\nOllie\nPavolia\nPekora\nPolka\nRikka\nRisu\nRoberu\nRoboco\nRushia\nSana\nShien\nShion\nSora\nSubaru\nSuisei\nTemma\nTowa\nWatame\nLuplus\nLui\n\nKoyori\nChloe\nIroha\nLaplus" | ${dmenucmd} -p "Which vtuber: ")

case $vtuber in
    Airani)
        $BROWSER "https://www.youtube.com/channel/UCAoy6rzhSf4ydcYjJw3WoVg";;
    Akirose)
        $BROWSER "https://www.youtube.com/channel/UCFTLzh12_nrtzqBPsTCqenA";;
    Amelia)
        $BROWSER "https://www.youtube.com/channel/UCyl1z3jo3XHR1riLFKG5UAg";;
    Anya)
        $BROWSER "https://www.youtube.com/channel/UC727SQYUvx5pDDGQpTICNWg";;
    Aqua)
        $BROWSER "https://www.youtube.com/channel/UC1opHUrw8rvnsadT-iGp7Cg";;
    Aruran)
        $BROWSER "https://www.youtube.com/channel/UCKeAhJvy8zgXWbh9duVjIaQ";;
    Astel)
        $BROWSER "https://www.youtube.com/channel/UCNVEsYbiZjH5QLmGeSgTSzg";;
    Ayame)
        $BROWSER "https://www.youtube.com/channel/UC7fk0CB07ly8oSl0aqKkqFg";;
    Azki)
        $BROWSER "https://www.youtube.com/channel/UC0TXe_LYZ4scaW2XMyi5_kw";;
    Baelz)
        $BROWSER "https://www.youtube.com/channel/UCgmPnx-EEeOrZSg5Tiw7ZRQ";;
    Botan)
        $BROWSER "https://www.youtube.com/channel/UCUKD-uaobj9jiqB-VXt71mA";;
    Calliope)
        $BROWSER "https://www.youtube.com/channel/UCL_qhgtOy0dy1Agp8vkySQg";;
    Choco)
        $BROWSER "https://www.youtube.com/channel/UC1suqwovbL1kzsoaZgFZLKg";;
    Fauna)
        $BROWSER "https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ";;
    Flare)
        $BROWSER "https://www.youtube.com/channel/UCvInZx9h3jC2JzsIzoOebWg";;
    Fubuki)
        $BROWSER "https://www.youtube.com/channel/UCdn5BQ06XqgXoAxIhbqw5Rg";;
    Gura)
        $BROWSER "https://www.youtube.com/channel/UCoSrY_IQQVpmIRZ9Xf-y93g";;
    Haachama)
        $BROWSER "https://www.youtube.com/channel/UC1CfXB_kRs3C-zaeTG3oGyg";;
    Holostars)
        $BROWSER "https://www.youtube.com/channel/UCWsfcksUUpoEvhia0_ut0bA";;
    Ina)
        $BROWSER "https://www.youtube.com/channel/UCMwGHR0BTZuLsmjY_NT5Pwg";;
    "HV Indonesia")
        $BROWSER "https://www.youtube.com/channel/UCfrWoRGlawPQDQxxeIDRP0Q";;
    Irys)
        $BROWSER "https://www.youtube.com/channel/UC8rcEBzJSleTkf_-agPM20g";;
    Izuru)
        $BROWSER "https://www.youtube.com/channel/UCZgOv3YDEs-ZnZWDYVwJdmA";;
    Kanata)
        $BROWSER "https://www.youtube.com/channel/UCZlDXzGoo7d44bwdNObFacg";;
    Kiara)
        $BROWSER "https://www.youtube.com/channel/UCHsx4Hqa-1ORjQTh9TYDhww";;
    Korone)
        $BROWSER "https://www.youtube.com/channel/UChAnqc_AY5_I3Px5dig3X1Q";;
    Kronii)
        $BROWSER "https://www.youtube.com/channel/UCmbs8T6MWqUHP1tIQvSgKrg";;
    Lamy)
        $BROWSER "https://www.youtube.com/channel/UCFKOVgVbGmX65RxO3EtH3iw";;
    Luna)
        $BROWSER "https://www.youtube.com/channel/UCa9Y57gfeY0Zro_noHRVrnw";;
    Marine)
        $BROWSER "https://www.youtube.com/channel/UCCzUftO8KOVkV4wQG1vkUvg";;
    Matsuri)
        $BROWSER "https://www.youtube.com/channel/UCQ0UDLQCjY0rmuxCDE38FGg";;
    Mel)
        $BROWSER "https://www.youtube.com/channel/UCD8HOxPs4Xvsm8H0ZxXGiBw";;
    Miko)
        $BROWSER "https://www.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA";;
    Mio)
        $BROWSER "https://www.youtube.com/channel/UCp-5t9SrOQwXMU7iIjQfARg";;
    Miyabi)
        $BROWSER "https://www.youtube.com/channel/UC6t3-_N8A6ME1JShZHHqOMw";;
    Moona)
        $BROWSER "https://www.youtube.com/channel/UCP0BspO_AMEe3aQqqpo89Dg";;
    Nanashi)
        $BROWSER "https://www.youtube.com/channel/UC3n5uGu18FoCy23ggWWp8tA";;
    Nene)
        $BROWSER "https://www.youtube.com/channel/UCAWSyEs_Io8MtpY3m-zqILA";;
    Noel)
        $BROWSER "https://www.youtube.com/channel/UCdyqAaZDKHXg4Ahi7VENThQ";;
    Oga)
        $BROWSER "https://www.youtube.com/channel/UCwL7dgTxKo8Y4RFIKWaf8gA";;
    Okayu)
        $BROWSER "https://www.youtube.com/channel/UCvaTdHTWBGv3MKj3KVqJVCw";;
    Ollie)
        $BROWSER "https://www.youtube.com/channel/UCYz_5n-uDuChHtLo7My1HnQ";;
    Pavolia)
        $BROWSER "https://www.youtube.com/channel/UChgTyjG-pdNvxxhdsXfHQ5Q";;
    Pekora)
        $BROWSER "https://www.youtube.com/channel/UC1DCedRgGHBdm81E1llLhOQ";;
    Polka)
        $BROWSER "https://www.youtube.com/channel/UCK9V2B22uJYu3N7eR_BT9QA";;
    Rikka)
        $BROWSER "https://www.youtube.com/channel/UC9mf_ZVpouoILRY9NUIaK-w";;
    Risu)
        $BROWSER "https://www.youtube.com/channel/UCOyYb1c43VlX9rc_lT6NKQw";;
    Roberu)
        $BROWSER "https://www.youtube.com/channel/UCANDOlYTJT7N5jlRC3zfzVA";;
    Rushia)
        $BROWSER "https://www.youtube.com/channel/UCl_gCybOJRIgOXw6Qb4qJzQ";;
    Sana)
        $BROWSER "https://www.youtube.com/channel/UCsUj0dszADCGbF3gNrQEuSQ";;
    Shien)
        $BROWSER "https://www.youtube.com/channel/UChSvpZYRPh0FvG4SJGSga3g";;
    Shion)
        $BROWSER "https://www.youtube.com/channel/UCXTpFs_3PqI41qX2d9tL2Rw";;
    Sora)
        $BROWSER "https://www.youtube.com/channel/UCp6993wxpyDPHUpavwDFqgg";;
    Subaru)
        $BROWSER "https://www.youtube.com/channel/UCvzGlP9oQwU--Y0r9id_jnA";;
    Suisei)
        $BROWSER "https://www.youtube.com/channel/UC5CwaMl1eIgY8h02uZw7u8A";;
    Temma)
        $BROWSER "https://www.youtube.com/channel/UCGNI4MENvnsymYjKiZwv9eg";;
    Towa)
        $BROWSER "https://www.youtube.com/channel/UC1uv2Oq6kNxgATlCiez59hw";;
    Watame)
        $BROWSER "https://www.youtube.com/channel/UCqm3BQLlJfvkTsX_hvm0UmA";;
    Laplus)
        $BROWSER "https://www.youtube.com/channel/UCENwRMx5Yh42zWpzURebzTw";;
    Lui)
        $BROWSER "https://www.youtube.com/channel/UCs9_O1tRPMQTHQ-N_L6FU2g";;
    Koyori)
        $BROWSER "https://www.youtube.com/channel/UC6eWCld0KwmyHFbAqK3V-Rw";;
    Chloe)
        $BROWSER "https://www.youtube.com/channel/UCIBY1ollUsauvVi4hW4cumw";;
    Iroha)
        $BROWSER "https://www.youtube.com/channel/UC_vMYWcDjmfdpH6r4TTn1MQ";;
esac
