#!/bin/bash

emerge --sync
find /var/log/portage -maxdepth 1 -type f -ls -delete # Clear logs
eclean-dist --deep; eclean-pkg --deep # Clear distfiles and package dependency

emerge --ask --update --verbose --deep --newuse @world
dispatch-conf

clear
eselect news read

emerge --depclean
