#!/bin/bash

pgrep -x dmenu && exit

mountableAndroid=$(simple-mtpfs -l)

chosen=$(echo "$mountableAndroid" | dmenu -h 27 -p "Which android")

name=$(echo $chosen | awk '{print $2}')
id=$(echo $chosen | cut -d : -f 1)

mkdir ~/"$name"

simple-mtpfs --device "$id" ~/"$name"
