#!/bin/bash

pgrep -x dmenu && exit

mountableDrives=$(lsblk -lp | grep 'part $' | awk '{print $1,"(" $4 ")"}')
[["$mountableDrives" == ""]] 2>/dev/null && exit 1

drive=$(echo "$mountableDrives" | dmenu -h 27 -p "Mount which drive?" | awk '{print $1}')
[[ "$drive" == "" ]] && exit 1

# if in /etc/fstab do that
mount "$drive" 2>/dev/null && exit 0

# if not in fstab
name=$(blkid $drive | grep -o ""LABEL.*"" | cut -d'"' -f2)
[[ ! -d /mnt/"$name" ]] && mkdir /mnt/"$name"

mount "$drive" /mnt/"$name"
