#!/bin/bash

pgrep -x dmenu && exit

unmountableDrives=$(lsblk -lp | grep 'part' | awk '{print $1,"(" $4 ")"}')
[["$unmountableDrives" == ""]] 2>/dev/null && exit 1

drive=$(echo "$unmountableDrives" | dmenu -h 27 -p "Unmount which drive?" | awk '{print $1}')
[[ "$drive" == "" ]] && exit 1

name=$(blkid $drive | grep -o ""LABEL.*"" | cut -d'"' -f2)
umount "$drive"
rmdir /mnt/"$name"
